language: java

# to make the build work with oraclejdk8: https://travis-ci.community/t/solved-oraclejdk8-installation-failing-still-again/3428
dist: trusty

sudo: false   # Linux OS: run in container

env:
  global:
    # get all the branches referencing this commit
    - TAG_BRANCH=$(git ls-remote origin | sed -n "\|$TRAVIS_COMMIT\s\+refs/heads/|{s///p}")

# Java 8 only
jdk: oraclejdk8
# Java 9 only
#jdk: oraclejdk9

addons:
  apt:
    packages:
      - p7zip-full
#    - oracle-java9-installer
# Java 9 only

before_install:
  - if [[ "${TRAVIS_OS_NAME}" == linux ]]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; fi

install: true

before_script:
#  - if [[ "${TRAVIS_OS_NAME}" == osx ]]; then brew update; brew cask reinstall caskroom/versions/java9; fi
# Java 9 only

cache:
  directories:
    - $HOME/.m2

script: mvn test -B

after_success:
  - .github/deploy_prepare.sh
#  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - .github/before_deploy.sh
deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file:
      - javadoc.zip
      - ./**/target/*!(javadoc|sources).jar
    skip_cleanup: true
    on:
      repo: martinfrancois/BoxplotFX
      tags: true
      all_branches: true
      condition: $TAG_BRANCH =~ ^(master|master-11)$
  - provider: script
    script: .github/deploy_bintray_central.sh
    on:
      repo: martinfrancois/BoxplotFX
      tags: true
      all_branches: true
      condition: $TAG_BRANCH =~ ^(master|master-11)$